/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_commonsware_android_tuning_lua_LuaActivity */

#ifndef _Included_com_commonsware_android_tuning_lua_LuaActivity
#define _Included_com_commonsware_android_tuning_lua_LuaActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_commonsware_android_tuning_lua_LuaActivity
 * Method:    executeLua
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_commonsware_android_tuning_lua_LuaActivity_executeLua
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
